can accept zip content in push via PIU request
zerocracy/baza pull request #143
Opened 2024-07-26 21:09 UTC by tank-bohr

fixes #135

2024-07-27 06:43 UTC, yegor256 commented on front/front_push.rb
> +def content_compressed?(content_encoding, content_type)
@tank-bohr what is the point of making such a small one-line function, in global scope? Can't you just inline it?

2024-07-27 06:43 UTC, yegor256 requested changes
@tank-bohr I suggest inlining the function

2024-07-27 07:06 UTC, yegor256 commented on front/front_push.rb
> +def save_content(io, target_path, content_encoding, content_type)
@tank-bohr I also don't think that it's a good idea to have this function in the global scope. Why can't you inline it? It's being used only once.

2024-07-28 04:51 UTC, tank-bohr commented on front/front_push.rb
> +def save_content(io, target_path, content_encoding, content_type)
Because the previous one was extracted, I tried to stick to the existing code style and didn't think it was in the global scope.
I extract functions not only to reuse them but also to give some chunk of code a name to show my intention. I believe it improves readability significantly.
But there is not much code here. I can easily inline it, so it should not be a problem.

2024-07-28 05:07 UTC, yegor256 requested changes
@tank-bohr one minor suggestion above

2024-07-28 05:07 UTC, yegor256 commented on front/front_push.rb
> +    readable_source = if request.env['HTTP_CONTENT_ENCODING'] == 'gzip' || request.env['HTTP_CONTENT_TYPE'] == 'application/zip'
@tank-bohr in general, it's a bad practice to give long/compound names to variables: https://www.yegor256.com/2015/01/12/compound-name-is-code-smell.html

2024-07-28 05:08 UTC, yegor256 commented
@tank-bohr also, please make sure you run `rake` before submitting changes. Currently, the build is broken in this branch, because of rubocop complaints.

2024-07-28 06:36 UTC, yegor256 commented
@tank-bohr it's better to format like this:

```
source =
  if ...
    ...
  else
    ...
  end
```

2024-07-28 07:22 UTC, yegor256 approved these changes
LGTM

2024-07-28 07:23 UTC, merged

2024-07-28 07:23 UTC, yegor256 commented
@tank-bohr thanks!

2024-07-28 08:08 UTC, 0crat commented
@yegor256 Thanks for the review! You've earned +25 points.  Your running balance is [-380](https://zerocracy.github.io/judges-action/zerocracy-vitals.html).

2024-07-28 09:08 UTC, 0crat commented
@tank-bohr Thanks for the contribution! You've earned +14 points for this: +20 as a basis; -6 for 6 comments of reviewers. Please, [keep](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) them coming. Your running balance is [+30](https://zerocracy.github.io/judges-action/zerocracy-vitals.html).

2024-08-10 13:20 UTC, 0crat commented
@tank-bohr Hey there! 👋 Thanks for your review, but remember, reviewing your own code isn't ideal. You've earned +5 points: +25 base, -40 for self-review, -10 for only 5 comments (we aim for 6+), and +30 to keep you motivated. Next time, try to hit at least 15 [hits-of-code](https://www.yegor256.com/2014/11/14/hits-of-code.html) and leave more comments for a bigger bonus! Your current balance is [+115](https://zerocracy.github.io/judges-action/zerocracy-vitals.html). Keep up the good work, and let's aim higher! 💪