enforces multiline assignment style
zerocracy/baza pull request #145
Opened 2024-07-28 07:34 UTC by tank-bohr

fixes #144

2024-07-28 14:59 UTC, yegor256 commented
@tank-bohr don't forget to [ping me](https://www.yegor256.com/2024/04/01/ping-me-please.html), otherwise I simply miss your pull requests

2024-07-28 15:01 UTC, yegor256 requested changes
@tank-bohr looks perfect, but check my comment above. Maybe we should fix Rubocop config somehow?

2024-07-28 15:01 UTC, yegor256 commented on .rubocop.yml
> +  Enabled: true
@tank-bohr I wonder, why it's not enabled by default? As far as I understand, Rubocop enforces _all_ rules by default, unless we disable them in the config file. If this is not true, then we have a bigger problem than this particular one.

2024-07-29 07:59 UTC, tank-bohr commented on .rubocop.yml
> +  Enabled: true
[Docs](https://docs.rubocop.org/rubocop/configuration.html#enabled) say:

> Most cops are enabled by default. Cops, introduced or significantly updated between major versions, are in a special pending status (read more in ["Versioning"](https://docs.rubocop.org/rubocop/versioning.html)). Some cops, configured the above Enabled: false in [config/default.yml](https://github.com/rubocop/rubocop/blob/master/config/default.yml), are disabled by default.


<img width="826" alt="изображение" src="https://github.com/user-attachments/assets/9af11f6b-6035-4e19-aa9b-71121e44a33a">


To change the defaults as far as I understand you need to

```yaml
AllCops:
  EnabledByDefault: true
```

2024-07-29 09:48 UTC, yegor256 commented
@tank-bohr let's add this maybe:

```
AllCops:
  EnabledByDefault: true
```

2024-07-29 11:51 UTC, closed without merging