#129 add `job.ip` column
zerocracy/baza pull request #154
Opened 2024-07-31 16:50 UTC by Suban05

## Changes
* Added column `ip` 
* `ip` added to `haml` files 
* Tests updated and added

2024-07-31 17:03 UTC, Suban05 commented
@yegor256 please, review it

2024-07-31 17:08 UTC, yegor256 requested changes
@Suban05 looks very good, one small comment above

2024-07-31 17:08 UTC, yegor256 commented on liquibase/2024/024-job-ip.xml
> +      ALTER TABLE job ADD COLUMN ip INET;
@Suban05 I believe, we should make it `NOT NULL` and also update all previous records, setting `0.0.0.0` to it.

2024-07-31 18:05 UTC, Suban05 commented on liquibase/2024/024-job-ip.xml
> +      ALTER TABLE job ADD COLUMN ip INET;
@yegor256 okay

2024-07-31 19:31 UTC, yegor256 commented
@rultor merge

2024-07-31 19:34 UTC, rultor commented
> @rultor merge

@yegor256 OK, I'll try to merge now. You can check the progress of the merge [here](https://www.rultor.com/t/42856-2261279946)

2024-07-31 19:46 UTC, merged

2024-07-31 19:47 UTC, rultor commented
> @rultor merge

@yegor256 Done! FYI, the full log is [here](https://www.rultor.com/t/42856-2261279946) (took me 11min)

2024-07-31 22:11 UTC, 0crat commented
@Suban05 Thanks for the review! You've earned +5 points for this: +25 as a basis; -40 for reviewing your own contribution (which is a bad idea); +20 to give you at least something.  Your running balance is [+71](https://zerocracy.github.io/judges-action/zerocracy-vitals.html).

2024-07-31 23:10 UTC, 0crat commented
@Suban05 Thanks for the contribution! You've earned +23 points for this: +30 as a basis; -7 for too many hits-of-code (201 >= 100). Please, [keep](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) them coming. Your running balance is [+76](https://zerocracy.github.io/judges-action/zerocracy-vitals.html).

2024-08-10 13:20 UTC, 0crat commented
@yegor256 Hey there! 👋 Great job on the review! You've snagged 32 points: 25 for being an awesome reviewer, and 7 for those thoughtful comments you made. 💡 Remember, more comments (up to 20) can boost your score even higher next time! Your current balance is [-581](https://zerocracy.github.io/judges-action/zerocracy-vitals.html). Keep up the good work, and you might hit that 80-point max soon! 🚀