#141 notify the user when a new token is added
zerocracy/baza pull request #226
Opened 2024-09-02 17:54 UTC by Suban05

Closes #141

2024-09-02 17:59 UTC, Suban05 commented
@Yegorov please review

2024-09-02 18:34 UTC, Yegorov requested changes
@Suban05 Looks good, but there are several comments

2024-09-02 18:34 UTC, Yegorov commented on test/baza/test_tokens.rb
> +    assert_empty(loog.to_s)
@Suban05 Maybe need more cases, when [token not added](https://github.com/zerocracy/baza/blob/master/objects/baza/tokens.rb#L46-L52):
* long name
* empty string name
* invalid name
* many active tokens already
* name already exists

2024-09-02 18:34 UTC, Yegorov commented on test/baza/test_tokens.rb
> +    assert_raises do
@Suban05 it will be looks better if you indicate what exception should raise, e. g.:
```ruby
assert_raises(RuntimeError) do
  human.tokens.add(nil)
end
```

2024-09-03 12:48 UTC, Yegorov approved these changes
@Suban05 perfect!

2024-09-03 13:29 UTC, Suban05 commented
@yegor256 please check

2024-09-03 17:18 UTC, merged

2024-09-03 17:18 UTC, yegor256 commented
@Suban05 thanks!

2024-09-03 20:31 UTC, 0crat commented
@Yegorov Thanks for your code review! Here's how your +4 points were calculated: +4 base points, -24 for self-review, +1.25 for 5 comments (capped at 8), -10 for fewer than 6 comments, +32.75 to meet the minimum 4-point reward. Your [running balance](https://zerocracy.github.io/judges-action/zerocracy-vitals.html) is now +416. Keep up the good work! 💻

2024-09-03 21:29 UTC, 0crat commented
@Suban05 Great work on your contribution! 🎉 You've earned +4 points, bringing your total to [+408](https://zerocracy.github.io/judges-action/zerocracy-vitals.html). While we'd love to see more comments next time, we appreciate your effort. [Keep the contributions coming](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) - you're making a valuable impact!