#142 notify the user when a new secret is added
zerocracy/baza pull request #227
Opened 2024-09-02 18:16 UTC by Suban05

Closes #142

2024-09-02 18:17 UTC, Suban05 commented
@Yegorov please review

2024-09-02 18:49 UTC, Yegorov requested changes
@Suban05 Looks good, but there are several comments

2024-09-02 18:49 UTC, Yegorov commented on test/baza/test_secrets.rb
> +    id = human.secrets.add(n, k, v)
@Suban05 Looks as [redundant vars](https://www.yegor256.com/2015/09/01/redundant-variables-are-evil.html), may be better as:
```ruby
id = human.secrets.add(fake_name, 'secret_key', SecureRandom.uuid)
```

2024-09-02 18:49 UTC, Yegorov commented on test/baza/test_secrets.rb
> +    assert_empty(loog.to_s)
@Suban05 Maybe need more cases, when [secret not added](https://github.com/zerocracy/baza/blob/master/objects/baza/secrets.rb#L84-L90)
And add what exception should raises, e. g.: `assert_raises(Baza::Urror)`

2024-09-03 07:27 UTC, Suban05 commented
@Yegorov updated

2024-09-03 13:29 UTC, Suban05 commented
@yegor256 please check

2024-09-03 17:18 UTC, merged

2024-09-03 17:18 UTC, yegor256 commented
@Suban05 thanks!

2024-09-03 20:31 UTC, 0crat commented
@Yegorov Thanks for your code review! Here's how your +4 points were calculated: +4 base points, -24 for self-review, +16 for hits-of-code (capped), -10 for <6 comments, +1.25 for 5 comments, and +16.75 to meet the minimum 4-point reward. Your [running balance](https://zerocracy.github.io/judges-action/zerocracy-vitals.html) is now +416. Keep up the good work! 💻

2024-09-03 21:29 UTC, 0crat commented
@Suban05 Hey there! 👋 Great job on your contribution! You've earned +4 points this time around. Here's the breakdown: +4 base points, -4 because we only got 5 comments (we're aiming for at least 6), and +4 to keep you motivated. Remember, more [hits-of-code](https://www.yegor256.com/2014/11/14/hits-of-code.html) and active code reviews can boost your points next time. [Keep](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) the contributions coming! Your current balance is [+408](https://zerocracy.github.io/judges-action/zerocracy-vitals.html). Let's aim higher for your next submission! 💪

2024-09-03 21:34 UTC, Yegorov commented
@yegor256 
> -24 for self-review

What does it mean "self-review"?